ML-Frontend/models/data_set_model.py
class DataSet:
    def __init__(self):
        self.model_name = ""
        self.independent_var_list = list()
        self.dependent_var = ""
        self.file_name = ""
        self.algorithm = ""

    @property
    def model_name(self):
        return self._model_name

    @model_name.setter
    def model_name(self, model_name_param):
        self._model_name = model_name_param

    @property
    def independent_var_list(self):
        return self._independent_var_list

    @independent_var_list.setter
    def independent_var_list(self, independent_var_list_param):
        self._independent_var_list = independent_var_list_param

    @property
    def dependent_var(self):
        return self._dependent_var

    @dependent_var.setter
    def dependent_var(self, dependent_var_param):
        self._dependent_var = dependent_var_param

    @property
    def file_name(self):
        return self._file_name

    @file_name.setter
    def file_name(self, file_name_param):
        self._file_name = file_name_param

    @property
    def algorithm(self):
        return self._algorithm

    @algorithm.setter
    def algorithm(self, algorithm_param):
        self._algorithm = algorithm_param

ML-Frontend/app.py
from flask import Flask
from flask_wtf.csrf import CSRFProtect
from views import home, machine_learning_view
from settings import DevelopmentConfig


def create_app():
    app = Flask(__name__)
    csrf = CSRFProtect()
    csrf.init_app(app)
    # load default configuration
    app.config.from_object(DevelopmentConfig())
    app.register_blueprint(home.bp)
    app.register_blueprint(machine_learning_view.bp)
    return app


app = create_app()

ML-Frontend/controllers/machine_learning_controller.py
import base64

import requests
import io
from PIL import Image
from models.data_set_model import DataSet
api_version = 0.1

API_URL_2 = f"http://127.0.0.1:5001/toolbox/api/{api_version}/ml-result"


def get_variables(file_name):
    file = {'file': open(f"upload/{file_name}", 'rb')}
    response = requests.post(url="http://127.0.0.1:5001/toolbox/api/0.1/ml-variables", files=file)
    variables = response.json()
    return variables["Variables"]


def sent_train_data(independent_var_list, dependent_var, algorithm, file_name):
    data_set = DataSet()
    data_set.model_name = "Serkan"
    data_set.algorithm = algorithm
    data_set.independent_var_list = independent_var_list
    data_set.dependent_var = dependent_var
    data_set.file_name = file_name
    # train_data = {"independent_var_list": independent_var_list, "dependent_var": dependent_var, "file_name": file_name,
    #                "algorithm": algorithm}
    response = requests.post(url=API_URL_2, json=data_set.__dict__)
    results = response.json()
    img_data = results["image"]
    img_data = str.encode(img_data)
    im = Image.open(io.BytesIO(base64.b64decode(img_data)))
    im.save('static/images/image1.png', 'PNG')
    return results["train_result"]

ML-Frontend/views/home.py
from flask import Blueprint, render_template

bp = Blueprint('home', __name__)


@bp.route('/', methods=['GET'])
def index():
    context_data = {
        "title": "NSH Toolbox"
    }
    return render_template("home.html", **context_data)

ML-Frontend/views/machine_learning_view.py
import os
from flask import Blueprint, render_template, request
from controllers.machine_learning_controller import *

bp = Blueprint('machine_learning', __name__)

variable = list()
file_name = ""
modified_variable = False


@bp.route('/machine-learning', methods=['GET', 'POST'])
def machine_learning():
    if request.method == "GET":
        context_data = {
            "title": "NSH Toolbox",
            "Variables": 0
        }
        return render_template("machine_learning.html", **context_data)
    elif request.method == "POST":
        if request.files['file'].filename != "":
            file = request.files['file']
            global file_name
            file_name = file.filename
            file.save(os.path.join("upload", file.filename))
            #  print(file.filename)
            variables = get_variables(file_name=file.filename)
            variables_modified = list()
            for item in variables:
                if " " in item:
                    global modified_variable
                    modified_variable = True
                variables_modified.append(item.replace(" ", "_"))
            global variable
            variable = variables_modified
            context_data = {
                "Variables": variables_modified,
                "Length": len(variables)
            }
            return render_template("machine_learning.html", **context_data)


@bp.route('/machine-learning-train', methods=['GET', 'POST'])
def train_model():
    if request.method == "POST":
        selected_algo = request.form.get('form_select_algo')
        print(selected_algo)
        #  print(variable)
        checked_list = list()

        for item in variable:
            check = request.form.get(f'{item + "_check"}')
            checked_list.append(check)

        independent_var = list()
        #  print("checklist1")
        for item, checked in zip(variable, checked_list):
            if checked == "True":
                #  print(item, "--->", checked)
                independent_var.append(item)

        checked_list_2 = list()
        for item in variable:
            check = request.form.get(f'{item + "_check_2"}')
            checked_list_2.append(check)
        dependant_var = ""
        for item, checked in zip(variable, checked_list_2):
            if checked == "True":
                #  print(item, "--->", checked)
                dependant_var = item

        if modified_variable:
            dependant_var = dependant_var.replace("_", " ")
            for index in range(0, len(independent_var)):
                independent_var[index] = independent_var[index].replace("_", " ")

        print(selected_algo)
        results = sent_train_data(independent_var_list=independent_var, dependent_var=dependant_var,
                                  file_name=file_name, algorithm=selected_algo)
        # intercept = results["Intercept"]
        # equation = ""
        # index = 1
        #  print(results["Coefficients"])
        # r2 = results["R2"]
        # for item in results["Coefficients"]:
        #     equation = equation + f"X{index}*" + str(item)
        #     index += 1

        context_data = {
            "R2": results["R2"],
        }
        return render_template("ml_result.html", **context_data)

ML-Frontend/templates/home.html
<!doctype html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <title>ML Tool</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="http://127.0.0.1:5000">Machine Learning Toolbox</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link" href="machine-learning">Machine Learning</a>
            </div>
        </div>
    </div>
</nav>

</br>

{% block page_content %}
{% endblock %}

<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
        crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
-->
</body>
</html>

ML-Frontend/templates/machine_learning.html
{% extends "home.html" %}


{% block page_content %}

<body>
{% if Variables == 0 %}
<form class="container" enctype=multipart/form-data action="{{ url_for('machine_learning.machine_learning') }}"
      method="post">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    <h1>Load Data</h1>
    <hr>
    <div class="card">
        <div class="card-header text-white bg-dark">Upload an CSV File</div>
        <div class="card-body">
            <div class="row">
                <!--                <div class="col col-md-2">-->
                <!--                    <label class="col-form-label">Upload CSV File</label>-->
                <!--                </div>-->
                <div class="col col-md-10">
                    <input name="file" type="file" class="form-control">
                </div>
                <div class="col col-lg-2">
                    <input class="btn btn-danger " type="submit" value="      Upload     ">
                </div>
            </div>
        </div>
    </div>
    </br>
</form>
{% else %}
<h1 align="center">Train Dataset</h1>
<hr>
<br>
<form class="container" enctype=multipart/form-data action="{{ url_for('machine_learning.train_model') }}"
      method="post">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    <div class="card">
        <div class="card-header text-white bg-dark">Data Preparation</div>
        <div class="card-body">
            <div class="row row-8">
                <h6> Please Select Scaler Method </h6>
                <br>
                <div class="col col-md-4">
                    <select class="form-select" name="form_select_scaler" aria-label="Default select example">
                        <option selected>Open this select menu</option>
                        <option value="none">No Scaler</option>
                        <option value="standard_scalar">Standard Scaler</option>
                    </select>
                </div>
            </div>
            <br>
            <div class="row row-8">
                <h6> Please Choose an Missing Values Handler Method </h6>
                <br>
                <div class="col col-md-4">
                    <select class="form-select" name="form_select_missing" aria-label="Default select example">
                        <option selected>Open this select menu</option>
                        <option value="drop_null">Drop null values</option>
                        <option value="drop_null">replace with mean</option>
                    </select>
                </div>
            </div>
            <br>

            <div class="row row-8">
                <h6> Please Choose Categorical Data Handler Method </h6>
                <br>
                <div class="col col-md-4">
                    <select class="form-select" name="form_select_categorical" aria-label="Default select example">
                        <option selected>Open this select menu</option>
                        <option value="label_encoder">Label Encoder</option>
                    </select>
                </div>
            </div>
        </div>
    </div>
    <br>
    <br>
    <div class="card">
        <div class="card-header text-white bg-dark">Feature Selection</div>
        <div class="card-body">
            <div class="row row-8">
                <h6>Please Choose the Independent Features</h6>
                <br>
            </div>
            {% for variable in Variables %}
            <div class="row row-8">
                <div class="col col-md-1">
                    <input class="form-check-input" name={{variable+"_check"}} type="checkbox" value="True"
                           id="flexCheckDefault">
                </div>
                <div class="col col-md-4">
                    <p>{{variable}}</p>
                </div>
            </div>
            {%endfor%}
            <hr>
            <div class="row row-8">
                <h6>Please Choose the Dependent Feature</h6>
                <br>
            </div>
            <br>
            {% for variable in Variables %}
            <div class="row row-8">
                <div class="col col-md-1">
                    <input class="form-check-input" name={{variable+"_check_2"}} type="checkbox" value="True"
                           id="flexCheckDefault1">
                </div>
                <div class="col col-md-4">
                    <p>{{variable}}</p>
                </div>
            </div>
            {%endfor%}
        </div>
    </div>
    <br>
    <div class="card">
        <div class="card-header text-white bg-dark">Choose the Algorithm</div>
        <div class="card-body">
            <div class="row row-8">
                <h6>Algorithm Selection</h6>
                <br>
            </div>
            <div class="row row-8">
                <div class="col col-md-4">
                    <select class="form-select" name="form_select_algo" aria-label="Default select example">
                        <option selected>Open this select menu</option>
                        <option value="linear_regression">Linear Regression</option>
                        <option value="polynomial_regression">Polynomial Regression</option>
                        <option value="svr">SVR</option>
                        <option value="decision_tree_regression">Decision Tree Regression</option>
                        <option value="random_forest_regression">Random Forest Regression</option>
                        <option value="logistic_regression">Logistic Regression</option>
                        <option value="random_forest_classification">Random Forest Classification</option>
                        <option value="naive_bayes">Naive Bayes</option>
                        <option value="kernel_svm">Kernel Svm</option>
                        <option value="k_nearest_neighbors">KNearest Neighbors Classification</option>
                        <option value="support_vector_machine">Support Vector Machine Classification</option>
                    </select>
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col col-md-12" align="right">
            <input class="btn btn-danger" type="submit" value="Generate">
        </div>
    </div>
</form>
{% endif %}


<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
        crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
-->
</body>

{% endblock %}

ML-Frontend/templates/ml_result.html
{% extends "home.html" %}


{% block page_content %}

<body>
<h1 align="center">Results</h1>
<hr>

<div class="card">
    <div class="card-header text-white bg-dark">Statistics</div>
    <div class="card-body">
        <div class="row row-10">
            <h6>R2 Value: {{R2}}</h6>
            <br>
        </div>
    </div>
</div>


<div class="card">
    <div class="card-header text-white bg-dark">Plot</div>
    <div class="card-body">
        <div class="row row-8">
            <img src='/static/images/image1.png' alt="User Image">
            <br>
        </div>
    </div>
</div>

</body>
{% endblock %}